# 날짜 데이터 전처리 과제 
- 데이터 : "6.세종시_오피스텔(매매)_실거래가.csv"

In [74]:
import pandas as pd 
df_sejong = pd.read_csv("../../data/6.세종시_오피스텔(매매)_실거래가.csv",encoding='utf8')

In [75]:
df_sejong

,계약년월,계약일,시군구,본번,부번,단지명,전용면적(㎡),거래금액(만원),층,건축년도,해제사유발생일
0,201701,4,세종특별자치시 어진동,0,0,푸르지오시티,23.74,"9,000",14,2014,NaN
1,201701,6,세종특별자치시 어진동,0,0,푸르지오시티,23.74,"9,500",11,2014,NaN
2,201702,5,세종특별자치시 나성동,713,0,세진이너스빌,34.15,"13,000",8,2013,NaN
3,201702,7,세종특별자치시 어진동,0,0,푸르지오시티,23.74,"9,500",4,2014,NaN
4,201702,7,세종특별자치시 어진동,0,0,푸르지오시티,23.74,"9,000",4,2014,NaN
...,...,...,...,...,...,...,...,...,...,...,...
340,202012,20,세종특별자치시 나성동,756,0,리치먼드시티세종,26.18,"16,410",6,2020,NaN
341,202012,21,세종특별자치시 어진동,0,0,푸르지오시티,24.22,"8,600",18,2014,NaN
342,202012,23,세종특별자치시 나성동,756,0,리치먼드시티세종,26.18,"15,340",7,2020,20210118.0
343,202012,23,세종특별자치시 어진동,0,0,2차푸르지오시티,30.48,"11,500",9,2014,NaN
344,202012,24,세종특별자치시 어진동,0,0,푸르지오시티,44.84,"15,600",18,2014,NaN

In [76]:
### 아래와 같이 계약년월을 datetime으로 변경하세요. 
df_sejong['계약년월'] = pd.to_datetime(df_sejong['계약년월'].astype(str),format="%Y%m") 
print(df_sejong)
print(df_sejong.info())

          계약년월  계약일          시군구   본번  부번       단지명  전용면적(㎡) 거래금액(만원)   층  \
0   2017-01-01    4  세종특별자치시 어진동    0   0    푸르지오시티    23.74    9,000  14
1   2017-01-01    6  세종특별자치시 어진동    0   0    푸르지오시티    23.74    9,500  11
2   2017-02-01    5  세종특별자치시 나성동  713   0    세진이너스빌    34.15   13,000   8
3   2017-02-01    7  세종특별자치시 어진동    0   0    푸르지오시티    23.74    9,500   4
4   2017-02-01    7  세종특별자치시 어진동    0   0    푸르지오시티    23.74    9,000   4
..         ...  ...          ...  ...  ..       ...      ...      ...  ..
340 2020-12-01   20  세종특별자치시 나성동  756   0  리치먼드시티세종    26.18   16,410   6
341 2020-12-01   21  세종특별자치시 어진동    0   0    푸르지오시티    24.22    8,600  18
342 2020-12-01   23  세종특별자치시 나성동  756   0  리치먼드시티세종    26.18   15,340   7
343 2020-12-01   23  세종특별자치시 어진동    0   0  2차푸르지오시티    30.48   11,500   9
344 2020-12-01   24  세종특별자치시 어진동    0   0    푸르지오시티    44.84   15,600  18

     건축년도     해제사유발생일
0    2014         NaN
1    2014         NaN
2    2013         NaN
3    2014         NaN
4    2014         NaN
..    ...         ...
340  2020         NaN
341  2014         NaN
342  2020  20210118.0
343  2014         NaN
344  2014         NaN

[345 rows x 11 columns]
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345 entries, 0 to 344
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   계약년월      345 non-null    datetime64[ns]
 1   계약일       345 non-null    int64
 2   시군구       345 non-null    object
 3   본번        345 non-null    int64
 4   부번        345 non-null    int64
 5   단지명       345 non-null    object
 6   전용면적(㎡)   345 non-null    float64
 7   거래금액(만원)  345 non-null    object
 8   층         345 non-null    int64
 9   건축년도      345 non-null    int64
 10  해제사유발생일   9 non-null      float64
dtypes: datetime64[ns](1), float64(2), int64(5), object(3)
memory usage: 29.8+ KB
None

In [77]:
## 계약년월을 아래와 같이 문자열로 다시 변경하세요. 
df_sejong['계약년월'] = df_sejong['계약년월'].dt.strftime("%Y_%m_%d")
df_sejong

,계약년월,계약일,시군구,본번,부번,단지명,전용면적(㎡),거래금액(만원),층,건축년도,해제사유발생일
0,2017_01_01,4,세종특별자치시 어진동,0,0,푸르지오시티,23.74,"9,000",14,2014,NaN
1,2017_01_01,6,세종특별자치시 어진동,0,0,푸르지오시티,23.74,"9,500",11,2014,NaN
2,2017_02_01,5,세종특별자치시 나성동,713,0,세진이너스빌,34.15,"13,000",8,2013,NaN
3,2017_02_01,7,세종특별자치시 어진동,0,0,푸르지오시티,23.74,"9,500",4,2014,NaN
4,2017_02_01,7,세종특별자치시 어진동,0,0,푸르지오시티,23.74,"9,000",4,2014,NaN
...,...,...,...,...,...,...,...,...,...,...,...
340,2020_12_01,20,세종특별자치시 나성동,756,0,리치먼드시티세종,26.18,"16,410",6,2020,NaN
341,2020_12_01,21,세종특별자치시 어진동,0,0,푸르지오시티,24.22,"8,600",18,2014,NaN
342,2020_12_01,23,세종특별자치시 나성동,756,0,리치먼드시티세종,26.18,"15,340",7,2020,20210118.0
343,2020_12_01,23,세종특별자치시 어진동,0,0,2차푸르지오시티,30.48,"11,500",9,2014,NaN
344,2020_12_01,24,세종특별자치시 어진동,0,0,푸르지오시티,44.84,"15,600",18,2014,NaN

In [78]:
df_sejong.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 345 entries, 0 to 344
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   계약년월      345 non-null    object
 1   계약일       345 non-null    int64
 2   시군구       345 non-null    object
 3   본번        345 non-null    int64
 4   부번        345 non-null    int64
 5   단지명       345 non-null    object
 6   전용면적(㎡)   345 non-null    float64
 7   거래금액(만원)  345 non-null    object
 8   층         345 non-null    int64
 9   건축년도      345 non-null    int64
 10  해제사유발생일   9 non-null      float64
dtypes: float64(2), int64(5), object(4)
memory usage: 29.8+ KB

In [82]:
df_sejong['계약월'] = list(map(lambda x: x[1],df_sejong['계약년월'].str.split("_")))
df_sejong

,계약년월,계약일,시군구,본번,부번,단지명,전용면적(㎡),거래금액(만원),층,건축년도,해제사유발생일,계약월
0,2017_01_01,4,세종특별자치시 어진동,0,0,푸르지오시티,23.74,"9,000",14,2014,NaN,01
1,2017_01_01,6,세종특별자치시 어진동,0,0,푸르지오시티,23.74,"9,500",11,2014,NaN,01
2,2017_02_01,5,세종특별자치시 나성동,713,0,세진이너스빌,34.15,"13,000",8,2013,NaN,02
3,2017_02_01,7,세종특별자치시 어진동,0,0,푸르지오시티,23.74,"9,500",4,2014,NaN,02
4,2017_02_01,7,세종특별자치시 어진동,0,0,푸르지오시티,23.74,"9,000",4,2014,NaN,02
...,...,...,...,...,...,...,...,...,...,...,...,...
340,2020_12_01,20,세종특별자치시 나성동,756,0,리치먼드시티세종,26.18,"16,410",6,2020,NaN,12
341,2020_12_01,21,세종특별자치시 어진동,0,0,푸르지오시티,24.22,"8,600",18,2014,NaN,12
342,2020_12_01,23,세종특별자치시 나성동,756,0,리치먼드시티세종,26.18,"15,340",7,2020,20210118.0,12
343,2020_12_01,23,세종특별자치시 어진동,0,0,2차푸르지오시티,30.48,"11,500",9,2014,NaN,12
344,2020_12_01,24,세종특별자치시 어진동,0,0,푸르지오시티,44.84,"15,600",18,2014,NaN,12

In [85]:
## 6월 데이터만 추출해보세요 
df_sejong.loc[df_sejong['계약월']=='06'].head(5)

,계약년월,계약일,시군구,본번,부번,단지명,전용면적(㎡),거래금액(만원),층,건축년도,해제사유발생일,계약월
21,2017_06_01,6,세종특별자치시 어진동,0,0,2차푸르지오시티,23.24,"9,300",10,2014,NaN,06
22,2017_06_01,8,세종특별자치시 어진동,0,0,푸르지오시티,24.22,"9,900",19,2014,NaN,06
23,2017_06_01,19,세종특별자치시 어진동,0,0,2차푸르지오시티,30.48,"14,800",15,2014,NaN,06
24,2017_06_01,21,세종특별자치시 어진동,0,0,호수의아침,24.01,"11,700",10,2014,NaN,06
64,2018_06_01,20,세종특별자치시 도담동,246,5,세종한신휴시티,32.19,"13,000",6,2014,NaN,06

In [86]:
## 날짜순으로 데이터를 정렬해보세요 
df_sejong.sort_values(by='계약년월')

,계약년월,계약일,시군구,본번,부번,단지명,전용면적(㎡),거래금액(만원),층,건축년도,해제사유발생일,계약월
0,2017_01_01,4,세종특별자치시 어진동,0,0,푸르지오시티,23.74,"9,000",14,2014,NaN,01
1,2017_01_01,6,세종특별자치시 어진동,0,0,푸르지오시티,23.74,"9,500",11,2014,NaN,01
7,2017_02_01,10,세종특별자치시 어진동,0,0,푸르지오시티,23.74,"9,600",13,2014,NaN,02
6,2017_02_01,9,세종특별자치시 도담동,246,5,세종한신휴시티,29.47,"13,000",6,2014,NaN,02
5,2017_02_01,8,세종특별자치시 어진동,0,0,푸르지오시티,22.42,"8,550",7,2014,NaN,02
...,...,...,...,...,...,...,...,...,...,...,...,...
335,2020_12_01,7,세종특별자치시 나성동,713,0,세진이너스빌,34.15,"12,000",5,2013,NaN,12
334,2020_12_01,5,세종특별자치시 어진동,0,0,푸르지오시티,22.42,"8,400",12,2014,NaN,12
333,2020_12_01,1,세종특별자치시 어진동,0,0,2차푸르지오시티,23.24,"7,700",5,2014,NaN,12
337,2020_12_01,9,세종특별자치시 나성동,756,0,리치먼드시티세종,26.18,"16,410",6,2020,NaN,12
344,2020_12_01,24,세종특별자치시 어진동,0,0,푸르지오시티,44.84,"15,600",18,2014,NaN,12